name: Install Scoop
description: Install Scoop package manager with verification and setup
inputs:
  create-cache:
    description: 'Whether to create the Scoop cache directory (required for some workflows)'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Install Scoop
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
        $installerUrl = 'https://raw.githubusercontent.com/ScoopInstaller/Install/ff4eedda58d832b8225d7697510f097ebe8ab071/install.ps1'
        $expectedHash = 'ef65c5a3d9f224d7c69a0e5d43008291f677e60c2f7898b132edbca4aaff021c'
        # Hash verified on 2025-12-13. Update expectedHash if the installer script is revised.
        $scoopInstaller = Join-Path $env:TEMP 'install-scoop.ps1'

        irm -Uri $installerUrl -OutFile $scoopInstaller -TimeoutSec 60 -ErrorAction Stop
        $installerHash = (Get-FileHash $scoopInstaller -Algorithm SHA256).Hash.ToLower()
        if ($installerHash -ne $expectedHash) {
            throw "Unexpected installer hash: $installerHash"
        }

        & $scoopInstaller
        "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        # Create cache directory if requested
        if ('${{ inputs.create-cache }}' -eq 'true') {
          $cachePath = Join-Path $env:USERPROFILE "scoop\cache"
          if (-not (Test-Path $cachePath)) {
            New-Item -ItemType Directory -Path $cachePath -Force | Out-Null
            Write-Output "Created Scoop cache directory at: $cachePath"
          }
        }
